name: ChatGPT PR Review

on: [pull_request]

jobs:
  chatgpt-review:
    name: ChatGPT Review
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: TensorAlchemy/LLM-Reviewer@main
        name: ChatGPT PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          temperature: 0.3
          review_per_file: true
          comment_per_file: true
